update workflow

diff --git a/.github/workflows/npm-publish-on-release.yml b/.github/workflows/npm-publish-on-release.yml
--- a/.github/workflows/npm-publish-on-release.yml
+++ b/.github/workflows/npm-publish-on-release.yml
@@ -33,12 +33,17 @@ jobs:
 
       - name: Validate package version
         run: |
-          CURRENT_VERSION=$(npm show . version)
           NEW_VERSION=$(node -p "require('./package.json').version")
-          if [ "$CURRENT_VERSION" = "$NEW_VERSION" ]; then
-            echo "The version $NEW_VERSION is already published. Exiting."
-            exit 1
+          if npm show stringwise version > /dev/null 2>&1; then
+            CURRENT_VERSION=$(npm show stringwise version)
+            if [ "$CURRENT_VERSION" = "$NEW_VERSION" ]; then
+              echo "The version $NEW_VERSION is already published. Exiting."
+              exit 1
+            fi
+          else
+            echo "Package not found in registry. Proceeding with first publish."
           fi
+
 
       - name: Authenticate to npm
         run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
